FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV ENVIRONMENT=dev

RUN apt-get update && \
    apt-get install -y curl gnupg apt-transport-https ca-certificates xz-utils wget dpkg && \
    \
    curl -fsSL https://repo.jellyfin.org/debian/jellyfin_team.gpg.key | gpg --dearmor -o /usr/share/keyrings/jellyfin-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/jellyfin-archive-keyring.gpg] https://repo.jellyfin.org/debian bullseye main" > /etc/apt/sources.list.d/jellyfin.list && \
    apt-get update && \
    \
    apt-get install -y jellyfin && \
    \
    wget https://repo.jellyfin.org/files/server/debian/latest-stable/arm64/jellyfin-web_10.10.7+deb12_all.deb && \
    dpkg -i jellyfin-web_10.10.7+deb12_all.deb || apt-get install -f -y && \
    rm jellyfin-web_10.10.7+deb12_all.deb && \
    \
    mkdir -p /usr/lib/jellyfin/bin/jellyfin-web && \
    cp -r /usr/share/jellyfin/web/* /usr/lib/jellyfin/bin/jellyfin-web/ && \
    \
    curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz \
    | tar -xJ -C /usr/local/bin --strip-components=1 --wildcards '*/ffmpeg' '*/ffprobe' && \
    chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe &&

EXPOSE 8096 8920 7359/udp 1900/udp

WORKDIR /var/lib/jellyfin

CMD ["jellyfin"]
