FROM debian:bullseye-slim AS base

LABEL org.opencontainers.image.authors="Mr.Lui Labas"
LABEL org.opencontainers.image.url="https://github.com/jgbry/b3e-docker-avance"
LABEL org.opencontainers.image.vendor="EfreiCorpInternationalWorldwideComapny"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y curl gnupg apt-transport-https ca-certificates xz-utils wget dpkg && \
    curl -fsSL https://repo.jellyfin.org/debian/jellyfin_team.gpg.key | gpg --dearmor -o /usr/share/keyrings/jellyfin-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/jellyfin-archive-keyring.gpg] https://repo.jellyfin.org/debian bullseye main" > /etc/apt/sources.list.d/jellyfin.list && \
    apt-get update && \
    apt-get install -y jellyfin && \
    wget https://repo.jellyfin.org/files/server/debian/latest-stable/arm64/jellyfin-web_10.10.7+deb12_all.deb && \
    dpkg -i jellyfin-web_10.10.7+deb12_all.deb || apt-get install -f -y && \
    rm jellyfin-web_10.10.7+deb12_all.deb && \
    mkdir -p /usr/lib/jellyfin/bin/jellyfin-web && \
    cp -r /usr/share/jellyfin/web/* /usr/lib/jellyfin/bin/jellyfin-web/ && \
    curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz \
    | tar -xJ -C /usr/local/bin --strip-components=1 --wildcards '*/ffmpeg' '*/ffprobe' && \
    chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache


RUN mkdir -p /var/lib/jellyfin && chown -R jellyfin:jellyfin /var/lib/jellyfin

EXPOSE 8096 8920 7359/udp 1900/udp

WORKDIR /var/lib/jellyfin

USER jellyfin

FROM base AS dev
ENV ENVIRONMENT=dev
CMD ["jellyfin"]

FROM base AS prod
ENV ENVIRONMENT=prod
ENTRYPOINT ["jellyfin"]